openapi: 3.0.0
info:
  title: Food Services
  description: Server for the food services aggregator application
  version: 1.0.1
paths:
  /address:
    post:
      summary: Set the address that will be used to search for available restaurants
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddressRequest"
      responses:
        '200':
          description:
            The address is returned in cookie named `address`. You need to include this cookie in subsequent requests.
          headers:
            Set-Cookie:
              schema:
                type: string
  /restaurants:
    get:
      summary: Return available restaurants from supported delivery providers
      parameters:
        - in: cookie
          name: address
          schema:
            type: string
          required: true
          description: "URL encoded address, returned by the POST /address endpoint"
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SummaryRestaurantResponse"
  /restaurants/{temporaryRestaurantUUID}:
    get:
      summary: Return aggregated restaurant information
      parameters:
        - in: path
          name: temporaryRestaurantUUID
          schema:
            type: string
          required: true
          description: Temporary restaurant identifier provided in the POST /restaurants response
        - in: cookie
          name: address
          schema:
            type: string
          required: true
          description: "URL encoded address, returned by the POST /address endpoint"
        - in: query
          name: subtotalCents
          schema:
            type: number
          required: true
          description: "estimated subtotal of the restaurant order"
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DetailedRestaurantResponse"

components:
  schemas:
    AddressRequest:
      type: object
      properties:
        address:
          type: string
        city:
          type: string
        province:
          type: string
        postalCode:
          type: string
        country:
          type: string
        latitude:
          type: number
        longitude:
          type: number

    SummaryRestaurantResponse:
      type: object
      properties:
        name:
          type: string
        imageUrl:
          type: string
        averageRating:
          type: number
        minEstimatedDeliveryTime:
          type: number
        maxEstimatedDeliveryTime:
          type: number
        id:
          $ref: "#/components/schemas/RestaurantId"

    DetailedRestaurantResponse:
      type: object
      properties:
        name:
          type: string
        imageUrl:
          type: string
        formattedAddress:
          type: string
        averageRating:
          type: number
        minEstimatedDeliveryTime:
          type: number
        maxEstimatedDeliveryTime:
          type: number
        serviceProviders:
          type: array
          items:
            $ref: "#/components/schemas/ServiceProviderRestaurantResponse"

    ServiceProviderRestaurantResponse:
      type: object
      properties:
        restaurantName:
          type: string
        redirectUrl:
          type: string
        serviceProviderName:
          $ref: "#/components/schemas/ServiceProviderNameEnum"
        fees:
          type: array
          items:
            $ref: "#/components/schemas/FeeResponse"
        menu:
          type: array
          items:
            $ref: "#/components/schemas/MenuCategoryResponse"

    MenuCategoryResponse:
      type: object
      properties:
        name:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/MenuItemResponse"

    MenuItemResponse:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        magnitude:
          type: number
        magnitudeUnit:
          $ref: "#/components/schemas/CurrencyUnitsEnum"
        currency:
          $ref: "#/components/schemas/CurrencyEnum"

    FeeResponse:
      type: object
      properties:
        type:
          $ref: "#/components/schemas/FeeTypeEnum"
        magnitude:
          type: number
        magnitudeUnits:
          $ref: "#/components/schemas/CurrencyUnitsEnum"
        currency:
          $ref: "#/components/schemas/CurrencyEnum"

    RestaurantId:
      type: string

    ############ ENUM DEFINITIONS ############
    ServiceProviderNameEnum:
      type: string
      enum:
        - SkipTheDishes
        - UberEats
        - Doordash
    FeeTypeEnum:
      type: string
      enum:
        - Delivery
        - Service
        - Small Order
    CurrencyEnum:
      type: string
      enum:
        - CAD
        - USD
    CurrencyUnitsEnum:
      type: string
      enum:
        - Dollars
        - Cents