openapi: 3.0.0
info:
  title: Food Services
  description: Server for the food services aggregator application
  version: 1.0.1
paths:
  /address:
    post:
      summary: Set the address that will be used to search for available restaurants
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Address"
      responses:
        '200':
          description:
            The session ID and address is returned in cookies named `SESSIONID` and `ADDRESS` respectively. You need to include these cookie in subsequent requests.
          headers:
            Set-Cookie:
              schema:
                type: string
  /restaurants:
    get:
      summary: Return available restaurants from supported delivery providers
      security:
        - cookieAuth: []
        - cookieAddress: []
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RestaurantPreview"
  /restaurants/{temporaryRestaurantUUID}:
    get:
      summary: Return aggregated restaurant information
      security:
        - cookieAuth: [ ]
        - cookieAddress: [ ]
      parameters:
        - in: path
          name: temporaryRestaurantUUID
          schema:
            type: string
          required: true
          description: Temporary restaurant identifier provided in the POST /restaurants response
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantAggregate"

components:
  schemas:
    Address:
      type: object
      properties:
        address:
          type: string
        city:
          type: string
        province:
          type: string
        postalCode:
          type: string
        country:
          type: string
        latitude:
          type: number
        longitude:
          type: number
    RestaurantPreviewMetadata:
      type: object
      properties:
        name:
          type: string
        imageUrl:
          type: string
        averageRating:
          type: number
        id:
          $ref: "#/components/schemas/RestaurantId"
    RestaurantPreview:
      allOf:
        - $ref: '#/components/schemas/RestaurantPreviewMetadata'
        - type: object
    RestaurantDetailedMetadata:
      type: object
      properties:
        name:
          type: string
        imageUrl:
          type: string
        id:
          $ref: "#/components/schemas/RestaurantId"
        formattedAddress:
          type: string
    RestaurantId:
      type: string
    ServiceProviderMetadata:
      type: object
      properties:
        name:
          type: string
        redirectUrl:
          type: string
    MenuItem:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        magnitude:
          type: number
        magnitudeUnit:
          $ref: "#/components/schemas/CurrencyUnits"
        currency:
          $ref: "#/components/schemas/Currency"
    MenuCategory:
      type: object
      properties:
        name:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/MenuItem"
    Fee:
      type: object
      properties:
        type:
          $ref: "#/components/schemas/FeeType"
        magnitude:
          type: number
        magnitudeUnits:
          $ref: "#/components/schemas/CurrencyUnits"
        currency:
          $ref: "#/components/schemas/Currency"

    ServiceProviderRestaurant:
      allOf:
        - $ref: "#/components/schemas/ServiceProviderMetadata"
        - type: object
          properties:
            fees:
              type: array
              items:
                $ref: "#/components/schemas/Fee"
            menu:
              type: array
              items:
                $ref: "#/components/schemas/MenuCategory"
    RestaurantAggregate:
      allOf:
        - $ref: "#/components/schemas/RestaurantDetailedMetadata"
        - type: object
          properties:
            serviceProviders:
              type: array
              items:
                $ref: "#/components/schemas/ServiceProviderRestaurant"

    ############ ENUM DEFINITIONS ############
    ServiceProviderName:
      type: string
      enum:
        - SkipTheDishes
        - UberEats
        - Doordash
    FeeType:
      type: string
      enum:
        - Delivery
        - Service
        - Small Order
    Currency:
      type: string
      enum:
        - CAD
        - USED
    CurrencyUnits:
      type: string
      enum:
        - Dollars
        - Cents
  ############ COOKIE DEFINITIONS ############
  securitySchemes:
    cookieSession:
      type: apiKey
      in: cookie
      name: SESSIONID
    cookieAddress:
      type: apiKey
      in: cookie
      name: ADDRESS