openapi: 3.0.0
info:
  title: Food Services
  description: Server for the food services aggregator application
  version: 1.0.1
paths:
  /restaurants:
    post:
      summary: Return available restaurants from supported delivery providers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressRequest'
      responses:
        '200':
          description: A list of available restaurants.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AddressRequest'

components:
  schemas:
    AddressRequest:
      type: object
      properties:
        formattedAddress:
          type: string